= Creating Machine Learning Models with Red Hat OpenShift Data Science
:navtitle: Home

Welcome to this quick course on the _Creating Machine Learning Models with Red Hat OpenShift Data Science_.
This course is the fourth in a series of 6 courses about Red Hat OpenShift Data Science:

1. https://redhatquickcourses.github.io/rhods-intro[Introduction to Red Hat OpenShift Data Science]
2. https://redhatquickcourses.github.io/rhods-admin[Red Hat OpenShift Data Science Administration]
3. Data Analysis and Visualization with Red Hat OpenShift Data Science (Under Development)
4. Creating Machine Learning Models with Red Hat OpenShift Data Science (_This course_)
5. https://redhatquickcourses.github.io/rhods-deploy[Deploying Machine Learning Models with Red Hat OpenShift Data Science]
6. https://redhatquickcourses.github.io/rhods-pipelines[Automation using Data Science Pipelines]

NOTE: After you have completed all the courses in the learning path, you can attempt the https://github.com/RedHatQuickCourses/rhods-qc-apps/tree/main/7.hands-on-lab["Hit the RHODS"] exercise, that tests your understanding of the concepts taught in all the courses.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Satyajit Lele
* Jaime Ramirez Castillo
* Max Murakami
* Sara Banderby
* Ravi Srinivasan

== Classroom Environment

There are two options, based on whether you are taking this course standalone (just this course), or as part of the full 6 course learning path where you installed RHODS on an OpenShift cluster in the second course in the learning path, _Red Hat OpenShift Data Science Administration_.

=== Option 1: Standalone (RHODS Pre-installed on OpenShift)

You will use the https://demo.redhat.com/catalog?search=openshift+data+science&item=babylon-catalog-prod%2Fsandboxes-gpte.ocp4-workshop-rhods-base-aws.prod[Base RHODS on AWS] catalog item in the Red Hat Demo Platform (RHDP) to run the hands on exercises in this course.

This classroom has a pre-installed version of Red Hat OpenShift Data Science on OpenShift. 

=== Option 2: Six Course Learning Path

Continue using the https://demo.redhat.com/catalog?search=Red+Hat+OpenShift+Container+Platform+4.13+Workshop&item=babylon-catalog-prod%2Fopenshift-cnv.ocp413-wksp-cnv.prod[Red Hat OpenShift Container Platform 4.13 Workshop] catalog item from the _Red Hat OpenShift Data Science Administration_ course.

This classroom does *NOT* have RHODS pre-installed. You are expected to complete the _Red Hat OpenShift Data Science Administration_ course, where you install and configure a basic RHODS instance, and then continue with this course.

== Prerequisites

* Take the Introduction to https://www.redhat.com/en/services/training/ad141-red-hat-training-presents-introduction-to-python-programming[Python Programming (AD141)] training course or demonstrate equivalent knowledge of Python programming
* Basic knowledge of machine learning foundations is recommended.
* Basic knowledge of the PyTorch Python library for machine learning and deep learning.

== Objectives

The overall objectives of this introductory course include:

* Describe basic machine learning concepts
* Describe the different types of machine learning 
* Create and train machine learning models
* Machine Learning Workflows
